# Generated by Django 4.0.3 on 2022-04-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_remove_sensor_measurement_sensor_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='measurement',
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='measurement.measurement'),
            preserve_default=False,
        ),
    ]
