# Generated by Django 4.0.3 on 2022-04-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_remove_sensor_measurement_measurement_sensor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('temperature', 'created_at')},
        ),
    ]
